import type { Locale } from "./language";

export const translations = {
  ru: {
    meta: {
      title: "Alexey Worker — цифровые продукты и автоматизация",
      description: "Сайты, Telegram-продукты, AI-инструменты, интеграции и автоматизация бизнес-процессов — от идеи до работающей системы.",
      ogTitle: "Alexey Worker — цифровые продукты, которые выполняют работу",
      ogDescription: "Разработка сайтов, Telegram-продуктов, AI-инструментов и автоматизации для бизнеса.",
      locale: "ru_RU",
    },
    header: {
      navLabel: "Основная навигация",
      mobileNavLabel: "Мобильная навигация",
      nav: [["Услуги", "/#services"], ["Работы", "/#projects"], ["Процесс", "/#process"], ["Обо мне", "/#about"]],
      cta: "Обсудить проект",
      openMenu: "Открыть меню",
      closeMenu: "Закрыть меню",
      languageLabel: "Выбор языка",
      switchTo: "Переключить язык на",
    },
    hero: {
      badge: "Разработчик цифровых продуктов",
      titleStart: "Создаю цифровые продукты, которые ",
      titleAccent: "выполняют работу",
      titleEnd: ", а не просто выглядят красиво.",
      description: "Сайты, Telegram-боты, AI-инструменты и автоматизация бизнес-процессов — от идеи до готовой работающей системы.",
      primary: "Обсудить проект",
      secondary: "Смотреть работы",
      rail: "САЙТЫ / TELEGRAM / AI / АВТОМАТИЗАЦИЯ",
      location: "GERMANY · РАБОТАЮ УДАЛЁННО",
      system: {
        aria: "Схема цифровой системы: интерфейс, AI, API и Telegram соединены с единым ядром",
        status: "СИСТЕМА / В СЕТИ",
        count: "04 МОДУЛЯ",
        core: "Ядро продукта",
        modules: [["WEB", "Интерфейс", "module--web"], ["AI", "Агент", "module--ai"], ["API", "Интеграции", "module--api"], ["TG", "Mini App", "module--tg"]],
        footer: ["Проектирование", "Интерфейс", "Логика", "Запуск"],
      },
    },
    services: {
      eyebrow: "Направления / 06",
      title: "От интерфейса до процессов за ним",
      text: "Проектирую продукт целиком: то, что видит пользователь, и то, что делает систему полезной для бизнеса.",
      liveStatus: "6 направлений объединяются в одну систему",
      liveHint: "Наведите на карточку, чтобы увидеть движение данных",
      clientGets: "Клиент получает",
      example: "Например",
      items: [
        { index: "01", title: "Сайты и веб-приложения", task: "Запустить продукт, объяснить сложную услугу или перевести процесс в удобный веб-интерфейс.", result: "Продуманная структура, адаптивный интерфейс и готовая к развитию кодовая база.", example: "Лендинг продукта, личный кабинет или сервис для клиентов." },
        { index: "02", title: "Telegram-боты и Mini Apps", task: "Сделать привычные действия доступными там, где пользователи уже общаются каждый день.", result: "Сценарии, платежи, уведомления и управление данными в едином Telegram-продукте.", example: "Бот клуба с внутренней экономикой и Mini App." },
        { index: "03", title: "AI-инструменты и агенты", task: "Ускорить работу с информацией, обращениями и повторяющимися интеллектуальными задачами.", result: "Управляемый AI-сценарий с понятными ограничениями, данными и контролем результата.", example: "Ассистент для обработки заявок и подготовки ответов." },
        { index: "04", title: "Автоматизация процессов", task: "Убрать ручные переносы данных, таблицы-дубли и действия, которые отнимают время команды.", result: "Связанный процесс с правилами, уведомлениями и прозрачными статусами.", example: "Автоматическая обработка заявки от формы до CRM." },
        { index: "05", title: "Панели управления", task: "Дать команде удобный контроль над пользователями, контентом, оплатами и операциями.", result: "Ролевой интерфейс с нужными метриками, фильтрами и безопасными действиями.", example: "Внутренняя панель оператора и администратора." },
        { index: "06", title: "Индивидуальные интеграции", task: "Соединить разрозненные сервисы в одну рабочую систему под конкретный процесс.", result: "Надёжный обмен данными, обработка ошибок и документация для развития.", example: "Связка сайта, CRM, платёжной системы и Telegram." },
      ],
    },
    projects: {
      eyebrow: "Избранные проекты",
      title: "Системы, собранные вокруг реальной задачи",
      text: "Без вымышленных метрик: показываю логику продукта, состав решения и роль каждого модуля.",
      openCase: "Открыть кейс",
      discuss: "Обсудить похожую задачу",
      items: [
        { kind: "Кейс 01", title: "PINK CLUB", eyeline: "@pinkclubgo_bot", description: "Telegram-система для русскоязычных создателей приватного цифрового контента. Закрытые материалы продаются дозированно, а не одним пакетом, формируя повторные покупки и способствуя росту продаж.", tags: ["Telegram Bot", "Монетизация", "Автоматизация", "Админ-панель"], href: "/projects/pink-club", externalUrl: "https://t.me/pinkclubgo_bot", status: "Развёрнутый кейс", tone: "pink", imageAlt: "Контурная схема iPhone с сердцем и логотипом PINK CLUB", visualStatus: "Система активна", visualLabels: ["Подарки", "Коллекция", "Топ фанс", "Без дублей"] },
        { kind: "Кейс 02", title: "PINK SCOUT", eyeline: "Обучаемый поиск лидов", description: "Система поиска лидов внутри отдельного Telegram-бота, которая учится на выборе пользователя. Принимает готовую базу или собирает её сама, извлекает нужные данные с сайтов и платформ и загружает результат в бот.", tags: ["Telegram Bot", "Парсинг данных", "Обучение", "Lead Search"], href: "/projects/pink-scout", externalUrl: "", status: "Развёрнутый кейс", tone: "blue", imageAlt: "Контурная анимация девушки-скаута, собирающей информацию", visualStatus: "Поиск запущен", visualLabels: ["Источники", "Фильтрация", "Обучение", "Выдача"] },
        { kind: "Кейс 03", title: "Система разработки с AI", eyeline: "Две нейросети · один процесс", description: "Автоматизация разработки, где одна нейросеть пишет код, а другая ставит задачи, проверяет результат, предлагает необходимые функции и контролирует качество их реализации.", tags: ["AI-разработка", "Проверка кода", "Оркестрация", "Автоматизация"], href: "/projects/ai-development-system", externalUrl: "", status: "Развёрнутый кейс", tone: "neutral", imageAlt: "Контурная схема управления разработкой двумя AI-моделями", visualStatus: "Цикл разработки", visualLabels: ["Постановка", "Код", "Проверка", "Улучшение"] },
      ],
    },
    journey: {
      label: "Ваш путь к решению",
      count: "6 понятных шагов",
      aria: "Путь клиента от первого контакта до решения бизнес-задачи",
      steps: [
        ["Связь со мной", "Вы описываете задачу"],
        ["Разбор", "Находим причину и цель"],
        ["Проектирование", "Формируем точное решение"],
        ["Разработка", "Собираю рабочую систему"],
        ["Запуск", "Проверяем в реальной работе"],
        ["Проблема решена", "Процесс работает и развивается"],
      ],
    },
    process: {
      eyebrow: "Подход к работе",
      title: "От неопределённой идеи до понятного запуска",
      text: "На выходе — не отдельный фрагмент кода, а продуманное решение, которое можно использовать, поддерживать и развивать.",
      steps: [
        ["Разбор задачи", "Фиксируем цель, ограничения, пользователей и критерии готовности."],
        ["Проектирование решения", "Собираю архитектуру, сценарии и состав продукта до начала разработки."],
        ["Дизайн интерфейса", "Выстраиваю понятный путь пользователя и состояния каждого экрана."],
        ["Разработка", "Собираю интерфейс, серверную логику, данные и внешние интеграции."],
        ["Тестирование", "Проверяю основные сценарии, ошибки, адаптивность и пограничные состояния."],
        ["Запуск и поддержка", "Помогаю развернуть продукт, наблюдаю за работой и развиваю по обратной связи."],
      ],
    },
    benefits: {
      eyebrow: "Почему так",
      title: "Цельная ответственность за результат",
      items: [
        ["Один ответственный за продукт", "Не нужно синхронизировать нескольких подрядчиков: архитектура, интерфейс и разработка остаются в одном контексте."],
        ["Решение под задачу", "Функции появляются не ради списка возможностей, а только когда помогают пользователю или бизнес-процессу."],
        ["Интерфейс как часть системы", "Продумываю не только экран, но и путь: первый запуск, ошибки, пустые состояния и ежедневную работу."],
        ["Меньше ручной работы", "Ищу места, где система может сама перенести данные, уведомить, проверить условие или подготовить результат."],
        ["Основа для развития", "Декомпозирую продукт на модули, чтобы новые сценарии можно было добавлять без полной пересборки."],
        ["Прозрачные этапы", "На каждом этапе понятно, что уже готово, какое решение принято и что будет происходить дальше."],
      ],
    },
    about: {
      eyebrow: "Обо мне",
      title: "Разработчик цифровых решений",
      lead: "Помогаю превратить бизнес-задачу в систему с понятной логикой, удобным интерфейсом и надёжной технической основой.",
      body: "Работаю на стыке проектирования, дизайна и разработки. Поэтому вижу не только отдельный экран или интеграцию, а весь пользовательский путь: от первого действия до данных в панели управления.",
      statOneTitle: "Полный цикл",
      statOne: "один контекст от идеи до запуска",
      statTwoTitle: "Продуктовое мышление",
      statTwo: "функции связаны с задачей",
    },
    contact: {
      kicker: "Начать проект / 2026",
      titleStart: "Есть идея или задача, которую пора ",
      titleAccent: "автоматизировать?",
      text: "Опишите, что должно работать. Я помогу превратить это в понятный цифровой продукт.",
      nameLabel: "Как вас зовут",
      namePlaceholder: "Имя",
      contactLabel: "Как связаться",
      contactPlaceholder: "@telegram или email",
      taskLabel: "Коротко о задаче",
      taskPlaceholder: "Что должно работать и для кого?",
      privacy: "Указанные данные используются только для ответа на заявку.",
      submit: "Отправить в Telegram",
      status: "Заявка подготовлена — отправьте её в открывшемся Telegram.",
      fallback: "Открыть Telegram вручную",
      messageTitle: "Новая заявка с сайта Alexey Worker",
      messageName: "Имя",
      messageContact: "Контакт",
      messageTask: "Задача",
      directTitle: "Или свяжитесь напрямую",
      telegram: "Telegram",
      email: "Email",
    },
    footer: { text: "Цифровые продукты и автоматизация для бизнеса.", top: "Наверх", telegram: "Telegram" },
    casePage: {
      metaTitle: "PINK CLUB — кейс цифровой системы | Alexey Worker",
      metaDescription: "PINK CLUB — Telegram-система монетизации приватного цифрового контента с коллекциями, ежедневными подарками, рейтингом и административной панелью.",
      back: "Все проекты",
      badge: "Кейс 01 / Telegram-продукт",
      intro: "@pinkclubgo_bot — цифровая система для русскоязычных создателей приватного контента: дозированная продажа закрытых материалов, игровые сценарии, персональные услуги и управление аудиторией.",
      openBot: "Открыть @pinkclubgo_bot",
      taskLabel: "Задача",
      taskTitle: "Превратить выдачу контента в управляемый сценарий повторных продаж",
      taskBodyOne: "Система разработана для русскоязычных создателей приватного цифрового контента. Вместо продажи всей библиотеки одним доступом она позволяет открывать закрытые материалы дозированно — через понятные действия, награды и персональные предложения.",
      taskBodyTwo: "Такой сценарий поддерживает интерес к продукту, создаёт больше поводов вернуться и способствует увеличению продаж без необходимости вручную сопровождать каждого пользователя.",
      solutionLabel: "Система / 06",
      solutionTitle: "Механика продукта и работа с данными",
      functions: [["Структура обработчиков", "Обработчики разделены по сценариям и надёжно работают с базой данных: система запоминает пользователей, материалы, коллекции, покупки, статусы и историю действий."], ["Дозированная монетизация", "Закрытые материалы выдаются поэтапно. Пользователь покупает конкретный доступ, а не получает весь объём контента сразу."], ["Ежедневный цикл", "Каждый день пользователи получают подарки, пополняют коллекцию и возвращаются, чтобы продолжать прогресс."], ["Рейтинг и награды", "Участники борются за лидирующие позиции, а лучшие получают награду по правилам продукта."], ["Личный раздел", "Через персональный раздел можно выбрать конкретную услугу и оплатить её в удобной валюте."], ["Защита от дублей", "Перед каждой выдачей система сверяется с историей пользователя и защищает его от повторного получения уже открытых материалов."]],
      adminLabel: "Управление аудиторией / 06",
      adminTitle: "Админ-панель для ежедневной работы модели",
      adminText: "Удобная панель объединяет контроль аудитории, заказов, коммуникаций и ключевых показателей. Основные операции выполняются без вмешательства в код.",
      adminTools: [["Статистика", "Собирает и показывает главные цифры проекта в одном месте."], ["Заказы", "Помогает обрабатывать автоматические покупки и ручные персональные заказы."], ["Пользователи", "Показывает полный список пользователей, информацию о них и уровни доступа."], ["Топ фанс", "Выделяет самых прибыльных пользователей с разделением по выбранному периоду."], ["Рассылка", "Отправляет сообщения всей аудитории или отдельным уровням пользователей."], ["Авто-сообщения", "Хранит удобный набор шаблонов разных форматов и содержания для регулярных рассылок от модели."]],
      resultLabel: "Результат",
      resultTitle: "Контент, продажи и аудитория работают как единая система",
      resultBody: "Архитектура объединяет Telegram-интерфейс, базу данных, выдачу материалов, платежи, игровые механики и административные сценарии. Дозированная модель доступа увеличила количество точек продажи и способствовала росту продаж, сохранив удобный путь для пользователя.",
      note: "Результат описан качественно: числовые показатели не публикуются без подтверждённых данных.",
      tech: "Технологический контур",
      next: "Следующий продукт",
      ctaTitle: "Нужна система с похожей логикой?",
      ctaText: "Опишите задачу — я предложу архитектуру, пользовательский сценарий и понятный план запуска без лишних модулей.",
      cta: "Обсудить задачу",
    },
    scoutCasePage: {
      metaTitle: "PINK SCOUT — кейс системы поиска лидов | Alexey Worker",
      metaDescription: "PINK SCOUT — Telegram-система поиска, фильтрации и выдачи лидов, которая обучается на выборе пользователя.",
      back: "Все проекты",
      badge: "Кейс 02 / Lead discovery",
      intro: "PINK SCOUT превращает поиск лидов в управляемый процесс внутри Telegram: собирает или принимает базу, извлекает нужные данные и обучается на выборе пользователя.",
      openBot: "",
      taskLabel: "Задача",
      taskTitle: "Сократить путь от разрозненных источников до подходящего лида",
      taskBodyOne: "Ручной поиск требует переходить между площадками, копировать данные и снова проверять каждую запись. PINK SCOUT объединяет эти действия в одном Telegram-интерфейсе.",
      taskBodyTwo: "Пользователь задаёт направление и отмечает подходящие результаты. Система запоминает выбор, уточняет критерии и делает следующую выдачу точнее.",
      solutionLabel: "Поиск / 06",
      solutionTitle: "Как данные превращаются в готовую подборку",
      functions: [["Подключение источников", "Система работает с готовой базой или формирует новую из разрешённых сайтов, платформ и внешних источников."], ["Сбор данных", "Отдельные обработчики загружают записи, сохраняют контекст источника и приводят информацию к единой структуре."], ["Извлечение признаков", "Из каждой записи выделяются параметры, по которым можно понять релевантность лида для поставленной задачи."], ["Обучение на выборе", "Подтверждения и отклонения пользователя становятся сигналами для уточнения следующих результатов."], ["Фильтрация и приоритет", "Неподходящие записи отсеиваются, а более релевантные поднимаются выше в выдаче."], ["Выдача в Telegram", "Готовые карточки поступают в бота, где их можно быстро просмотреть, оценить и продолжить поиск."]],
      adminLabel: "Контроль поиска / 06",
      adminTitle: "Рабочее пространство для управления подборками",
      adminText: "Параметры поиска, источники, обратная связь и история результатов остаются в одном контексте — без ручной сборки новых таблиц.",
      adminTools: [["Источники", "Показывает подключённые площадки и состояние получения данных."], ["Импорт базы", "Принимает подготовленные данные и проверяет структуру перед обработкой."], ["Критерии", "Хранит активные признаки поиска и уточнения, сделанные пользователем."], ["Сессии поиска", "Разделяет подборки по задачам, чтобы сигналы разных направлений не смешивались."], ["Карточки лидов", "Собирает найденные данные в читаемый формат для быстрого решения."], ["История и экспорт", "Сохраняет обработанные результаты и позволяет продолжить работу вне бота."]],
      resultLabel: "Результат",
      resultTitle: "Поиск становится повторяемым процессом, а не ручным исследованием",
      resultBody: "Архитектура соединяет источники, обработку данных, пользовательскую обратную связь и Telegram-выдачу. Система сохраняет накопленный контекст и может развиваться под новые направления поиска.",
      note: "Кейс описывает реализованную логику продукта без публикации неподтверждённых количественных показателей.",
      tech: "Технологический контур",
      next: "Ваш следующий продукт",
      ctaTitle: "Нужно автоматизировать поиск и отбор данных?",
      ctaText: "Расскажите, где сейчас ищутся лиды и по каким признакам определяется качество. Я помогу собрать управляемый сценарий.",
      cta: "Обсудить систему",
    },
    aiCasePage: {
      metaTitle: "AI Development System — кейс автоматизации разработки | Alexey Worker",
      metaDescription: "Система разработки, где ведущая AI-модель управляет задачами, вторая пишет код, а отдельный контур проверяет качество результата.",
      back: "Все проекты",
      badge: "Кейс 03 / AI-оркестрация",
      intro: "Система автоматизирует цикл разработки: ведущая AI-модель планирует работу и проверяет результат, исполнитель пишет код, а контрольный контур не пропускает изменения без проверки.",
      openBot: "",
      taskLabel: "Задача",
      taskTitle: "Сделать AI-разработку последовательной и контролируемой",
      taskBodyOne: "Одна модель может быстро писать код, но без устойчивого контекста терять требования, пропускать ошибки и принимать локальные решения в ущерб продукту.",
      taskBodyTwo: "Поэтому роли разделены: ведущая модель хранит цель и декомпозирует работу, модель-исполнитель реализует задачи, а результат проходит автоматическую проверку.",
      solutionLabel: "Цикл / 06",
      solutionTitle: "Как две AI-модели ведут продукт от задачи до проверки",
      functions: [["Постановка задачи", "Ведущая модель переводит цель продукта в конкретную задачу с ограничениями и критериями готовности."], ["Контекст продукта", "Перед разработкой система собирает связанные файлы, решения и требования, необходимые именно для текущего изменения."], ["Написание кода", "Модель-исполнитель реализует задачу в заданных границах и фиксирует, какие части системы были изменены."], ["Ревью результата", "Ведущая модель сопоставляет код с требованиями, архитектурой и ожидаемым пользовательским сценарием."], ["Автоматические проверки", "Сборка, типы, тесты и структурные правила становятся обязательным шлюзом перед принятием результата."], ["Улучшение продукта", "Если в процессе выявлена необходимая функция, ведущая модель формулирует её как отдельную задачу и контролирует реализацию."]],
      adminLabel: "Контроль качества / 06",
      adminTitle: "Роли и проверки не смешиваются в одном запросе",
      adminText: "Каждый этап оставляет проверяемый результат. Это помогает сохранять продуктовый контекст и видеть, почему система приняла или вернула изменение.",
      adminTools: [["AI-руководитель", "Удерживает цель, планирует задачи и принимает решение о готовности."], ["AI-разработчик", "Пишет код по точному заданию, не меняя область работы без причины."], ["Quality gate", "Запускает обязательные проверки и блокирует результат при ошибках."], ["Критерии готовности", "Связывает каждое изменение с понятными требованиями к поведению продукта."], ["История решений", "Сохраняет ход работы, замечания ревью и причины внесённых изменений."], ["Человеческий контроль", "Оставляет владельцу продукта финальное решение для значимых архитектурных шагов."]],
      resultLabel: "Результат",
      resultTitle: "Код создаётся внутри управляемого инженерного цикла",
      resultBody: "Вместо одиночной генерации система формирует последовательность: задача, контекст, реализация, ревью, проверка и улучшение. Такой подход делает AI полезным участником разработки, не отдавая ему бесконтрольное управление продуктом.",
      note: "Описание отражает архитектуру процесса; показатели скорости и качества не публикуются без отдельного измерения.",
      tech: "Технологический контур",
      next: "Ваш следующий продукт",
      ctaTitle: "Хотите встроить AI в реальный рабочий процесс?",
      ctaText: "Опишите повторяющуюся интеллектуальную задачу. Я спроектирую роли моделей, контроль качества и безопасные границы автоматизации.",
      cta: "Обсудить AI-систему",
    },
  },
  en: {
    meta: {
      title: "Alexey Worker — digital products and automation",
      description: "Websites, Telegram products, AI tools, integrations and business process automation — from idea to a working system.",
      ogTitle: "Alexey Worker — digital products that get work done",
      ogDescription: "Websites, Telegram products, AI tools and business automation built end to end.",
      locale: "en_US",
    },
    header: {
      navLabel: "Primary navigation",
      mobileNavLabel: "Mobile navigation",
      nav: [["Services", "/#services"], ["Projects", "/#projects"], ["Process", "/#process"], ["About", "/#about"]],
      cta: "Discuss a project",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      languageLabel: "Language selection",
      switchTo: "Switch language to",
    },
    hero: {
      badge: "Digital product developer",
      titleStart: "I create digital products that ",
      titleAccent: "get work done",
      titleEnd: ", not just look good.",
      description: "Websites, Telegram bots, AI tools and business process automation — from the first idea to a complete working system.",
      primary: "Discuss a project",
      secondary: "View projects",
      rail: "WEB / TELEGRAM / AI / AUTOMATION",
      location: "GERMANY · WORKING REMOTELY",
      system: {
        aria: "Digital system diagram: interface, AI, API and Telegram connected to one product core",
        status: "SYSTEM / ONLINE",
        count: "04 MODULES",
        core: "Product core",
        modules: [["WEB", "Interface", "module--web"], ["AI", "Agent", "module--ai"], ["API", "Gateway", "module--api"], ["TG", "Mini App", "module--tg"]],
        footer: ["Planning", "Interface", "Logic", "Launch"],
      },
    },
    services: {
      eyebrow: "Expertise / 06",
      title: "From the interface to the processes behind it",
      text: "I design the entire product: what users see and what makes the system valuable to the business.",
      liveStatus: "6 disciplines connected into one system",
      liveHint: "Hover over a card to see the data flow",
      clientGets: "What you get",
      example: "Example",
      items: [
        { index: "01", title: "Websites and web apps", task: "Launch a product, explain a complex service or move a workflow into a clear web interface.", result: "Thoughtful structure, responsive interface and a codebase ready to evolve.", example: "A product landing page, customer account or client-facing service." },
        { index: "02", title: "Telegram bots and Mini Apps", task: "Put important actions where your users already communicate every day.", result: "Flows, payments, notifications and data management in one Telegram product.", example: "A club bot with an internal economy and Mini App." },
        { index: "03", title: "AI tools and agents", task: "Speed up information work, request handling and repeatable knowledge tasks.", result: "A controlled AI workflow with clear guardrails, data sources and human oversight.", example: "An assistant that processes requests and drafts responses." },
        { index: "04", title: "Process automation", task: "Remove manual data transfers, duplicate spreadsheets and repetitive team operations.", result: "A connected workflow with rules, notifications and transparent statuses.", example: "Automated request handling from a form to the CRM." },
        { index: "05", title: "Control panels", task: "Give the team convenient control over users, content, payments and operations.", result: "A role-based interface with useful metrics, filters and safe actions.", example: "An internal operator and administrator dashboard." },
        { index: "06", title: "Custom integrations", task: "Connect separate services into one reliable system for a specific process.", result: "Reliable data exchange, error handling and documentation for future development.", example: "A website, CRM, payment platform and Telegram connected together." },
      ],
    },
    projects: {
      eyebrow: "Selected projects",
      title: "Systems built around a real problem",
      text: "No fictional metrics: I show the product logic, solution structure and the role of every module.",
      openCase: "Open case study",
      discuss: "Discuss a similar challenge",
      items: [
        { kind: "Case 01", title: "PINK CLUB", eyeline: "@pinkclubgo_bot", description: "A Telegram system for Russian-speaking private digital content creators. Gated materials are sold in measured releases instead of one complete package, encouraging repeat purchases and supporting sales growth.", tags: ["Telegram Bot", "Monetization", "Automation", "Admin Panel"], href: "/projects/pink-club", externalUrl: "https://t.me/pinkclubgo_bot", status: "Full case study", tone: "pink", imageAlt: "Line-art iPhone with a heart and the PINK CLUB logotype", visualStatus: "System online", visualLabels: ["Daily gifts", "Collection", "Top fans", "No duplicates"] },
        { kind: "Case 02", title: "PINK SCOUT", eyeline: "Adaptive lead discovery", description: "A lead search system inside a dedicated Telegram bot that learns from the user's choices. It accepts an existing database or builds one, extracts relevant data from websites and platforms, and delivers the result to the bot.", tags: ["Telegram Bot", "Data Parsing", "Learning", "Lead Search"], href: "/projects/pink-scout", externalUrl: "", status: "Full case study", tone: "blue", imageAlt: "Line-art scout woman collecting and filtering information", visualStatus: "Search running", visualLabels: ["Sources", "Filtering", "Learning", "Delivery"] },
        { kind: "Case 03", title: "AI Development System", eyeline: "Two AI models · one workflow", description: "A development automation workflow where one AI writes code while another directs the work, reviews the result, proposes useful features and controls the quality of their implementation.", tags: ["AI Development", "Code Review", "Orchestration", "Automation"], href: "/projects/ai-development-system", externalUrl: "", status: "Full case study", tone: "neutral", imageAlt: "Line-art workflow with one AI directing another AI and a quality gate", visualStatus: "Development loop", visualLabels: ["Direction", "Code", "Review", "Improve"] },
      ],
    },
    journey: {
      label: "Your path to a solution",
      count: "6 clear steps",
      aria: "Client journey from the first contact to a solved business problem",
      steps: [["Contact me", "You describe the challenge"], ["Discovery", "We identify the cause and goal"], ["Solution design", "We define the exact system"], ["Development", "I build the working product"], ["Launch", "We validate it in real use"], ["Problem solved", "The process works and can evolve"]],
    },
    process: {
      eyebrow: "How I work",
      title: "From an uncertain idea to a clear launch",
      text: "You receive more than a fragment of code: a considered solution that can be used, maintained and developed.",
      steps: [["Discovery", "We define the goal, constraints, users and completion criteria."], ["Solution design", "I map the architecture, flows and product scope before development begins."], ["Interface design", "I create a clear user journey and every important screen state."], ["Development", "I build the interface, server logic, data layer and external integrations."], ["Testing", "I verify core journeys, errors, responsiveness and edge cases."], ["Launch and support", "I deploy the product, monitor how it works and improve it using feedback."]],
    },
    benefits: {
      eyebrow: "Why this works",
      title: "One clear responsibility for the outcome",
      items: [["One person owns the product", "You do not have to synchronize several contractors: architecture, interface and development stay in one context."], ["Built for the actual problem", "Features are added only when they help a user or improve the business process."], ["The interface is part of the system", "I design beyond a screen: onboarding, errors, empty states and everyday operations all matter."], ["Less manual work", "I find where the system can transfer data, notify, verify a condition or prepare a result automatically."], ["A foundation that can evolve", "The product is split into modules so new scenarios can be added without rebuilding everything."], ["Transparent stages", "At every stage you know what is ready, which decisions were made and what happens next."]],
    },
    about: {
      eyebrow: "About me",
      title: "Digital solutions developer",
      lead: "I turn business challenges into systems with clear logic, thoughtful interfaces and a reliable technical foundation.",
      body: "I work across product planning, design and development. That lets me see the complete user journey — from the first action to the data available in the control panel.",
      statOneTitle: "Full cycle",
      statOne: "one context from idea to launch",
      statTwoTitle: "Product thinking",
      statTwo: "every feature supports the goal",
    },
    contact: {
      kicker: "Start a project / 2026",
      titleStart: "Have an idea or a task that should be ",
      titleAccent: "automated?",
      text: "Describe what needs to work. I will help turn it into a clear digital product.",
      nameLabel: "Your name",
      namePlaceholder: "Name",
      contactLabel: "How to reach you",
      contactPlaceholder: "@telegram or email",
      taskLabel: "About the challenge",
      taskPlaceholder: "What should work, and for whom?",
      privacy: "The details you provide are used only to respond to your request.",
      submit: "Send via Telegram",
      status: "Your message is ready — send it in the Telegram window that opened.",
      fallback: "Open Telegram manually",
      messageTitle: "New request from the Alexey Worker website",
      messageName: "Name",
      messageContact: "Contact",
      messageTask: "Challenge",
      directTitle: "Or contact me directly",
      telegram: "Telegram",
      email: "Email",
    },
    footer: { text: "Digital products and business automation.", top: "Back to top", telegram: "Telegram" },
    casePage: {
      metaTitle: "PINK CLUB — digital system case study | Alexey Worker",
      metaDescription: "PINK CLUB is a Telegram monetization system for private digital content with collections, daily gifts, rankings and an administration panel.",
      back: "All projects",
      badge: "Case 01 / Telegram product",
      intro: "@pinkclubgo_bot is a digital system for Russian-speaking private content creators: measured sales of gated materials, engagement mechanics, personal services and audience management.",
      openBot: "Open @pinkclubgo_bot",
      taskLabel: "Challenge",
      taskTitle: "Turn content delivery into a controlled repeat-sales journey",
      taskBodyOne: "The system was developed for Russian-speaking creators of private digital content. Instead of selling the entire library at once, it releases gated materials in measured steps through clear actions, rewards and personal offers.",
      taskBodyTwo: "This journey sustains interest, creates more reasons to return and supports sales growth without requiring manual guidance for every user.",
      solutionLabel: "System / 06",
      solutionTitle: "Product mechanics and data handling",
      functions: [["Handler architecture", "Handlers are separated by journey and work reliably with the database: the system remembers users, materials, collections, purchases, statuses and action history."], ["Measured monetization", "Gated materials are delivered step by step. A user buys specific access instead of receiving the entire content library at once."], ["Daily engagement loop", "Users receive daily gifts, grow their collection and return to continue their progress."], ["Ranking and rewards", "Members compete for leading positions, while top participants receive rewards according to product rules."], ["Personal services", "A dedicated personal section lets users choose a specific service and pay in a convenient currency."], ["Duplicate protection", "Before every delivery the system checks user history and prevents previously unlocked materials from being issued again."]],
      adminLabel: "Audience management / 06",
      adminTitle: "An administration panel for daily creator operations",
      adminText: "The panel brings audience control, orders, communications and key indicators into one clear workspace. Core operations require no code changes.",
      adminTools: [["Statistics", "Collects and displays the project's most important figures in one place."], ["Orders", "Supports both automated purchases and manually handled personal orders."], ["Users", "Displays the full user list, user details and access-level segmentation."], ["Top fans", "Highlights the most profitable users across selected time periods."], ["Broadcasts", "Sends any message to the full audience or selected access levels."], ["Automated messages", "Provides reusable message templates in different formats and styles for the creator's recurring campaigns."]],
      resultLabel: "Outcome",
      resultTitle: "Content, sales and audience management work as one system",
      resultBody: "The architecture connects the Telegram interface, database, content delivery, payments, engagement mechanics and administration. The measured-access model created more sales touchpoints and supported sales growth while keeping the experience clear for users.",
      note: "The outcome is described qualitatively; numerical metrics are not published without verified data.",
      tech: "Technology stack",
      next: "Your next product",
      ctaTitle: "Need a system with similar logic?",
      ctaText: "Describe the challenge and I will propose the architecture, user journey and a clear launch plan without unnecessary modules.",
      cta: "Discuss the challenge",
    },
    scoutCasePage: {
      metaTitle: "PINK SCOUT — lead discovery system case study | Alexey Worker",
      metaDescription: "PINK SCOUT is a Telegram system that finds, filters and delivers leads while learning from user choices.",
      back: "All projects",
      badge: "Case 02 / Lead discovery",
      intro: "PINK SCOUT turns lead discovery into a controlled Telegram workflow: it builds or accepts a database, extracts relevant data and learns from user choices.",
      openBot: "",
      taskLabel: "Challenge",
      taskTitle: "Shorten the journey from scattered sources to a relevant lead",
      taskBodyOne: "Manual discovery requires switching between platforms, copying data and checking every record again. PINK SCOUT brings those actions into one Telegram interface.",
      taskBodyTwo: "The user sets a direction and marks useful results. The system remembers those choices, refines its criteria and improves the next delivery.",
      solutionLabel: "Search / 06",
      solutionTitle: "How raw data becomes a ready-to-use shortlist",
      functions: [["Source connection", "The system works with an existing database or builds a new one from permitted websites, platforms and external sources."], ["Data collection", "Dedicated handlers load records, preserve source context and normalize the information into one structure."], ["Signal extraction", "Each record is analysed for the attributes that indicate relevance to the current task."], ["Learning from choices", "User approvals and rejections become signals that refine future results."], ["Filtering and priority", "Irrelevant records are removed while stronger matches move higher in the delivery."], ["Telegram delivery", "Ready lead cards arrive in the bot, where they can be reviewed, rated and used to continue the search."]],
      adminLabel: "Search control / 06",
      adminTitle: "A workspace for managing discovery sessions",
      adminText: "Search parameters, sources, feedback and result history stay in one context without rebuilding spreadsheets by hand.",
      adminTools: [["Sources", "Shows connected platforms and the current data collection state."], ["Database import", "Accepts prepared datasets and validates their structure before processing."], ["Criteria", "Stores active search signals and user refinements."], ["Search sessions", "Keeps separate tasks isolated so feedback from different directions does not mix."], ["Lead cards", "Turns collected data into a readable format for fast decisions."], ["History and export", "Preserves processed results and supports continued work outside the bot."]],
      resultLabel: "Outcome",
      resultTitle: "Discovery becomes a repeatable workflow instead of manual research",
      resultBody: "The architecture connects sources, data processing, user feedback and Telegram delivery. It preserves accumulated context and can evolve for new discovery directions.",
      note: "The case study describes implemented product logic without publishing unverified quantitative claims.",
      tech: "Technology stack",
      next: "Your next product",
      ctaTitle: "Need to automate data search and qualification?",
      ctaText: "Tell me where leads are currently found and what defines a strong match. I will help design a controlled workflow.",
      cta: "Discuss the system",
    },
    aiCasePage: {
      metaTitle: "AI Development System — automation case study | Alexey Worker",
      metaDescription: "A development system where a lead AI directs tasks, a second AI writes code and a separate quality layer checks every result.",
      back: "All projects",
      badge: "Case 03 / AI orchestration",
      intro: "The system automates the development loop: a lead AI plans and reviews the work, an implementation AI writes code, and a quality layer prevents unchecked changes from passing.",
      openBot: "",
      taskLabel: "Challenge",
      taskTitle: "Make AI-assisted development sequential and controlled",
      taskBodyOne: "A single model can write code quickly, but without stable context it may lose requirements, miss issues or optimize a local change at the product's expense.",
      taskBodyTwo: "The roles are separated: the lead model preserves the goal and decomposes the work, the implementation model completes tasks, and every result goes through automated checks.",
      solutionLabel: "Loop / 06",
      solutionTitle: "How two AI models move a product from task to verification",
      functions: [["Task direction", "The lead model turns a product goal into a specific task with constraints and completion criteria."], ["Product context", "Before implementation, the system gathers the files, decisions and requirements relevant to the current change."], ["Code implementation", "The implementation model completes the task within its defined scope and records which parts were changed."], ["Result review", "The lead model compares the code against requirements, architecture and the intended user journey."], ["Automated checks", "Builds, types, tests and structural rules become a mandatory gate before acceptance."], ["Product improvement", "When a necessary feature is identified, the lead model defines it as a separate task and oversees its implementation."]],
      adminLabel: "Quality control / 06",
      adminTitle: "Roles and checks are not mixed in one prompt",
      adminText: "Every stage leaves a verifiable result. This preserves product context and makes it clear why a change was accepted or returned.",
      adminTools: [["Lead AI", "Preserves the goal, plans tasks and decides whether work is ready."], ["Developer AI", "Writes code from a precise brief without expanding scope without reason."], ["Quality gate", "Runs mandatory checks and blocks results when errors remain."], ["Completion criteria", "Connects every change to clear product behaviour requirements."], ["Decision history", "Preserves the work log, review notes and reasons behind changes."], ["Human control", "Keeps final approval for meaningful architectural decisions with the product owner."]],
      resultLabel: "Outcome",
      resultTitle: "Code is produced inside a controlled engineering loop",
      resultBody: "Instead of one-off generation, the system creates a sequence: task, context, implementation, review, verification and improvement. AI becomes a useful development participant without receiving uncontrolled authority over the product.",
      note: "This description reflects the process architecture; speed and quality claims require separate measurement and are not invented here.",
      tech: "Technology stack",
      next: "Your next product",
      ctaTitle: "Want to embed AI into a real operating workflow?",
      ctaText: "Describe the repeatable knowledge task. I will design model roles, quality control and safe automation boundaries.",
      cta: "Discuss an AI system",
    },
  },
} as const;

export function getTranslations(locale: Locale) {
  return translations[locale];
}
