import type { Locale } from "./language";

export const translations = {
  ru: {
    meta: {
      title: "Alexey Worker — цифровые продукты и автоматизация",
      description: "Сайты, Telegram-продукты, AI-инструменты, интеграции и автоматизация бизнес-процессов — от идеи до работающей системы.",
      ogTitle: "Alexey Worker — цифровые продукты, которые выполняют работу",
      ogDescription: "Разработка сайтов, Telegram-продуктов, AI-инструментов и автоматизации для бизнеса.",
      locale: "ru_RU",
    },
    header: {
      navLabel: "Основная навигация",
      mobileNavLabel: "Мобильная навигация",
      nav: [["Услуги", "/#services"], ["Работы", "/#projects"], ["Процесс", "/#process"], ["Обо мне", "/#about"]],
      cta: "Обсудить проект",
      openMenu: "Открыть меню",
      closeMenu: "Закрыть меню",
      languageLabel: "Выбор языка",
      switchTo: "Переключить язык на",
    },
    hero: {
      badge: "Разработчик цифровых продуктов",
      titleStart: "Создаю цифровые продукты, которые ",
      titleAccent: "выполняют работу",
      titleEnd: ", а не просто выглядят красиво.",
      description: "Сайты, Telegram-боты, AI-инструменты и автоматизация бизнес-процессов — от идеи до готовой работающей системы.",
      primary: "Обсудить проект",
      secondary: "Смотреть работы",
      rail: "САЙТЫ / TELEGRAM / AI / АВТОМАТИЗАЦИЯ",
      location: "GERMANY · РАБОТАЮ УДАЛЁННО",
      system: {
        aria: "Схема цифровой системы: интерфейс, AI, API и Telegram соединены с единым ядром",
        status: "СИСТЕМА / В СЕТИ",
        count: "04 МОДУЛЯ",
        core: "Ядро продукта",
        modules: [["WEB", "Интерфейс", "module--web"], ["AI", "Агент", "module--ai"], ["API", "Интеграции", "module--api"], ["TG", "Mini App", "module--tg"]],
        footer: ["Проектирование", "Интерфейс", "Логика", "Запуск"],
      },
    },
    services: {
      eyebrow: "Направления / 06",
      title: "От интерфейса до процессов за ним",
      text: "Проектирую продукт целиком: то, что видит пользователь, и то, что делает систему полезной для бизнеса.",
      liveStatus: "6 направлений объединяются в одну систему",
      liveHint: "Наведите на карточку, чтобы увидеть движение данных",
      clientGets: "Клиент получает",
      example: "Например",
      items: [
        { index: "01", title: "Сайты и веб-приложения", task: "Запустить продукт, объяснить сложную услугу или перевести процесс в удобный веб-интерфейс.", result: "Продуманная структура, адаптивный интерфейс и готовая к развитию кодовая база.", example: "Лендинг продукта, личный кабинет или сервис для клиентов." },
        { index: "02", title: "Telegram-боты и Mini Apps", task: "Сделать привычные действия доступными там, где пользователи уже общаются каждый день.", result: "Сценарии, платежи, уведомления и управление данными в едином Telegram-продукте.", example: "Бот клуба с внутренней экономикой и Mini App." },
        { index: "03", title: "AI-инструменты и агенты", task: "Ускорить работу с информацией, обращениями и повторяющимися интеллектуальными задачами.", result: "Управляемый AI-сценарий с понятными ограничениями, данными и контролем результата.", example: "Ассистент для обработки заявок и подготовки ответов." },
        { index: "04", title: "Автоматизация процессов", task: "Убрать ручные переносы данных, таблицы-дубли и действия, которые отнимают время команды.", result: "Связанный процесс с правилами, уведомлениями и прозрачными статусами.", example: "Автоматическая обработка заявки от формы до CRM." },
        { index: "05", title: "Панели управления", task: "Дать команде удобный контроль над пользователями, контентом, оплатами и операциями.", result: "Ролевой интерфейс с нужными метриками, фильтрами и безопасными действиями.", example: "Внутренняя панель оператора и администратора." },
        { index: "06", title: "Индивидуальные интеграции", task: "Соединить разрозненные сервисы в одну рабочую систему под конкретный процесс.", result: "Надёжный обмен данными, обработка ошибок и документация для развития.", example: "Связка сайта, CRM, платёжной системы и Telegram." },
      ],
    },
    projects: {
      eyebrow: "Избранные проекты",
      title: "Системы, собранные вокруг реальной задачи",
      text: "Без вымышленных метрик: показываю логику продукта, состав решения и роль каждого модуля.",
      openCase: "Открыть кейс",
      discuss: "Обсудить похожую задачу",
      items: [
        { kind: "Кейс 01", title: "PINK CLUB", description: "Telegram-продукт как единая цифровая система клуба: пользовательские сценарии, внутренняя экономика, автоматизация и управление.", tags: ["Telegram", "Mini App", "Автоматизация", "Админ-панель"], href: "/projects/pink-club", status: "Развёрнутый кейс", tone: "pink", image: "/images/projects/pink-club-device.png", imageAlt: "Премиальный смартфон с интерфейсом цифрового продукта PINK CLUB" },
        { kind: "Кейс 02", title: "Сервис заявок", description: "Каркас кейса для системы, которая объединяет сайт, маршрутизацию обращений и статусы обработки.", tags: ["Веб-приложение", "CRM", "API"], href: "/#contact", status: "Материалы готовятся", tone: "blue", image: "/images/projects/request-platform-device.png", imageAlt: "Смартфон с интерфейсом автоматизированного маршрута заявок" },
        { kind: "Кейс 03", title: "AI-ассистент команды", description: "Каркас кейса для AI-инструмента: поиск по базе знаний, подготовка ответов и контроль человеком.", tags: ["AI-агент", "База знаний", "Процессы"], href: "/#contact", status: "Концепция", tone: "neutral", image: "/images/projects/ai-assistant-device.png", imageAlt: "Смартфон с премиальным интерфейсом AI-ассистента" },
      ],
    },
    journey: {
      label: "Ваш путь к решению",
      count: "6 понятных шагов",
      aria: "Путь клиента от первого контакта до решения бизнес-задачи",
      steps: [
        ["Связь со мной", "Вы описываете задачу"],
        ["Разбор", "Находим причину и цель"],
        ["Проектирование", "Формируем точное решение"],
        ["Разработка", "Собираю рабочую систему"],
        ["Запуск", "Проверяем в реальной работе"],
        ["Проблема решена", "Процесс работает и развивается"],
      ],
    },
    process: {
      eyebrow: "Подход к работе",
      title: "От неопределённой идеи до понятного запуска",
      text: "На выходе — не отдельный фрагмент кода, а продуманное решение, которое можно использовать, поддерживать и развивать.",
      steps: [
        ["Разбор задачи", "Фиксируем цель, ограничения, пользователей и критерии готовности."],
        ["Проектирование решения", "Собираю архитектуру, сценарии и состав продукта до начала разработки."],
        ["Дизайн интерфейса", "Выстраиваю понятный путь пользователя и состояния каждого экрана."],
        ["Разработка", "Собираю интерфейс, серверную логику, данные и внешние интеграции."],
        ["Тестирование", "Проверяю основные сценарии, ошибки, адаптивность и пограничные состояния."],
        ["Запуск и поддержка", "Помогаю развернуть продукт, наблюдаю за работой и развиваю по обратной связи."],
      ],
    },
    benefits: {
      eyebrow: "Почему так",
      title: "Цельная ответственность за результат",
      items: [
        ["Один ответственный за продукт", "Не нужно синхронизировать нескольких подрядчиков: архитектура, интерфейс и разработка остаются в одном контексте."],
        ["Решение под задачу", "Функции появляются не ради списка возможностей, а только когда помогают пользователю или бизнес-процессу."],
        ["Интерфейс как часть системы", "Продумываю не только экран, но и путь: первый запуск, ошибки, пустые состояния и ежедневную работу."],
        ["Меньше ручной работы", "Ищу места, где система может сама перенести данные, уведомить, проверить условие или подготовить результат."],
        ["Основа для развития", "Декомпозирую продукт на модули, чтобы новые сценарии можно было добавлять без полной пересборки."],
        ["Прозрачные этапы", "На каждом этапе понятно, что уже готово, какое решение принято и что будет происходить дальше."],
      ],
    },
    about: {
      eyebrow: "Обо мне",
      title: "Разработчик цифровых решений",
      lead: "Помогаю превратить бизнес-задачу в систему с понятной логикой, удобным интерфейсом и надёжной технической основой.",
      body: "Работаю на стыке проектирования, дизайна и разработки. Поэтому вижу не только отдельный экран или интеграцию, а весь пользовательский путь: от первого действия до данных в панели управления.",
      statOneTitle: "Полный цикл",
      statOne: "один контекст от идеи до запуска",
      statTwoTitle: "Продуктовое мышление",
      statTwo: "функции связаны с задачей",
    },
    contact: {
      kicker: "Начать проект / 2026",
      titleStart: "Есть идея или задача, которую пора ",
      titleAccent: "автоматизировать?",
      text: "Опишите, что должно работать. Я помогу превратить это в понятный цифровой продукт.",
      nameLabel: "Как вас зовут",
      namePlaceholder: "Имя",
      contactLabel: "Как связаться",
      contactPlaceholder: "@telegram или email",
      taskLabel: "Коротко о задаче",
      taskPlaceholder: "Что должно работать и для кого?",
      privacy: "Указанные данные используются только для ответа на заявку.",
      submit: "Отправить в Telegram",
      status: "Заявка подготовлена — отправьте её в открывшемся Telegram.",
      fallback: "Открыть Telegram вручную",
      messageTitle: "Новая заявка с сайта Alexey Worker",
      messageName: "Имя",
      messageContact: "Контакт",
      messageTask: "Задача",
      directTitle: "Или свяжитесь напрямую",
      telegram: "Telegram",
      email: "Email",
    },
    footer: { text: "Цифровые продукты и автоматизация для бизнеса.", top: "Наверх", telegram: "Telegram" },
    casePage: {
      metaTitle: "PINK CLUB — кейс цифровой системы | Alexey Worker",
      metaDescription: "Проектирование Telegram-продукта: Mini App, пользовательские сценарии, внутренняя экономика, административная панель и интеграции.",
      back: "Все проекты",
      badge: "Кейс 01 / Telegram-продукт",
      intro: "Цифровая система клуба внутри Telegram: пользовательские сценарии, внутренняя экономика, автоматизация, администрирование и инфраструктура.",
      taskLabel: "Задача",
      taskTitle: "Собрать не отдельного бота, а цельный Telegram-продукт",
      taskBodyOne: "Клубу нужен единый пользовательский путь: знакомство с продуктом, участие в сценариях, работа с внутренними единицами и обратная связь — без ручного сопровождения каждого действия.",
      taskBodyTwo: "Решение проектируется как система связанных модулей. Это позволяет разделить интерфейс, бизнес-логику и управление, не разрывая опыт пользователя.",
      solutionLabel: "Решение / 04",
      solutionTitle: "Основные контуры продукта",
      functions: [["Telegram-first сценарии", "Вход, навигация и ключевые действия встроены в привычную среду пользователя."], ["Внутренняя экономика", "Модель баланса, операций и правил спроектирована как отдельный контролируемый контур."], ["Административная панель", "Управление участниками, контентом и событиями без вмешательства в код."], ["Автоматизация", "Система сама обрабатывает стандартные события, меняет статусы и отправляет уведомления."]],
      resultLabel: "Результат",
      resultTitle: "Основа, на которой можно развивать продукт",
      resultBody: "Архитектура объединяет Telegram-интерфейс, Mini App, серверную логику, хранение данных и административные сценарии. Каждый модуль можно развивать независимо, сохраняя единый продуктовый контекст.",
      note: "Количественные показатели намеренно не приведены: для кейса используются только подтверждённые сведения о составе и логике решения.",
      tech: "Технологический контур",
      next: "Следующий продукт",
      ctaTitle: "Нужна система с похожей логикой?",
      cta: "Обсудить задачу",
    },
  },
  en: {
    meta: {
      title: "Alexey Worker — digital products and automation",
      description: "Websites, Telegram products, AI tools, integrations and business process automation — from idea to a working system.",
      ogTitle: "Alexey Worker — digital products that get work done",
      ogDescription: "Websites, Telegram products, AI tools and business automation built end to end.",
      locale: "en_US",
    },
    header: {
      navLabel: "Primary navigation",
      mobileNavLabel: "Mobile navigation",
      nav: [["Services", "/#services"], ["Projects", "/#projects"], ["Process", "/#process"], ["About", "/#about"]],
      cta: "Discuss a project",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      languageLabel: "Language selection",
      switchTo: "Switch language to",
    },
    hero: {
      badge: "Digital product developer",
      titleStart: "I create digital products that ",
      titleAccent: "get work done",
      titleEnd: ", not just look good.",
      description: "Websites, Telegram bots, AI tools and business process automation — from the first idea to a complete working system.",
      primary: "Discuss a project",
      secondary: "View projects",
      rail: "WEB / TELEGRAM / AI / AUTOMATION",
      location: "GERMANY · WORKING REMOTELY",
      system: {
        aria: "Digital system diagram: interface, AI, API and Telegram connected to one product core",
        status: "SYSTEM / ONLINE",
        count: "04 MODULES",
        core: "Product core",
        modules: [["WEB", "Interface", "module--web"], ["AI", "Agent", "module--ai"], ["API", "Gateway", "module--api"], ["TG", "Mini App", "module--tg"]],
        footer: ["Planning", "Interface", "Logic", "Launch"],
      },
    },
    services: {
      eyebrow: "Expertise / 06",
      title: "From the interface to the processes behind it",
      text: "I design the entire product: what users see and what makes the system valuable to the business.",
      liveStatus: "6 disciplines connected into one system",
      liveHint: "Hover over a card to see the data flow",
      clientGets: "What you get",
      example: "Example",
      items: [
        { index: "01", title: "Websites and web apps", task: "Launch a product, explain a complex service or move a workflow into a clear web interface.", result: "Thoughtful structure, responsive interface and a codebase ready to evolve.", example: "A product landing page, customer account or client-facing service." },
        { index: "02", title: "Telegram bots and Mini Apps", task: "Put important actions where your users already communicate every day.", result: "Flows, payments, notifications and data management in one Telegram product.", example: "A club bot with an internal economy and Mini App." },
        { index: "03", title: "AI tools and agents", task: "Speed up information work, request handling and repeatable knowledge tasks.", result: "A controlled AI workflow with clear guardrails, data sources and human oversight.", example: "An assistant that processes requests and drafts responses." },
        { index: "04", title: "Process automation", task: "Remove manual data transfers, duplicate spreadsheets and repetitive team operations.", result: "A connected workflow with rules, notifications and transparent statuses.", example: "Automated request handling from a form to the CRM." },
        { index: "05", title: "Control panels", task: "Give the team convenient control over users, content, payments and operations.", result: "A role-based interface with useful metrics, filters and safe actions.", example: "An internal operator and administrator dashboard." },
        { index: "06", title: "Custom integrations", task: "Connect separate services into one reliable system for a specific process.", result: "Reliable data exchange, error handling and documentation for future development.", example: "A website, CRM, payment platform and Telegram connected together." },
      ],
    },
    projects: {
      eyebrow: "Selected projects",
      title: "Systems built around a real problem",
      text: "No fictional metrics: I show the product logic, solution structure and the role of every module.",
      openCase: "Open case study",
      discuss: "Discuss a similar challenge",
      items: [
        { kind: "Case 01", title: "PINK CLUB", description: "A Telegram product built as one digital club system: user journeys, internal economy, automation and management.", tags: ["Telegram", "Mini App", "Automation", "Admin"], href: "/projects/pink-club", status: "Full case study", tone: "pink", image: "/images/projects/pink-club-device.png", imageAlt: "Premium smartphone presenting the PINK CLUB digital product interface" },
        { kind: "Case 02", title: "Request platform", description: "A case framework for a system connecting a website, request routing and processing statuses.", tags: ["Web App", "CRM", "API"], href: "/#contact", status: "Materials in progress", tone: "blue", image: "/images/projects/request-platform-device.png", imageAlt: "Smartphone presenting an automated request routing interface" },
        { kind: "Case 03", title: "Team AI assistant", description: "A case framework for an AI tool: knowledge search, response drafting and human review.", tags: ["AI Agent", "Knowledge Base", "Workflow"], href: "/#contact", status: "Concept", tone: "neutral", image: "/images/projects/ai-assistant-device.png", imageAlt: "Smartphone presenting a premium AI assistant interface" },
      ],
    },
    journey: {
      label: "Your path to a solution",
      count: "6 clear steps",
      aria: "Client journey from the first contact to a solved business problem",
      steps: [["Contact me", "You describe the challenge"], ["Discovery", "We identify the cause and goal"], ["Solution design", "We define the exact system"], ["Development", "I build the working product"], ["Launch", "We validate it in real use"], ["Problem solved", "The process works and can evolve"]],
    },
    process: {
      eyebrow: "How I work",
      title: "From an uncertain idea to a clear launch",
      text: "You receive more than a fragment of code: a considered solution that can be used, maintained and developed.",
      steps: [["Discovery", "We define the goal, constraints, users and completion criteria."], ["Solution design", "I map the architecture, flows and product scope before development begins."], ["Interface design", "I create a clear user journey and every important screen state."], ["Development", "I build the interface, server logic, data layer and external integrations."], ["Testing", "I verify core journeys, errors, responsiveness and edge cases."], ["Launch and support", "I deploy the product, monitor how it works and improve it using feedback."]],
    },
    benefits: {
      eyebrow: "Why this works",
      title: "One clear responsibility for the outcome",
      items: [["One person owns the product", "You do not have to synchronize several contractors: architecture, interface and development stay in one context."], ["Built for the actual problem", "Features are added only when they help a user or improve the business process."], ["The interface is part of the system", "I design beyond a screen: onboarding, errors, empty states and everyday operations all matter."], ["Less manual work", "I find where the system can transfer data, notify, verify a condition or prepare a result automatically."], ["A foundation that can evolve", "The product is split into modules so new scenarios can be added without rebuilding everything."], ["Transparent stages", "At every stage you know what is ready, which decisions were made and what happens next."]],
    },
    about: {
      eyebrow: "About me",
      title: "Digital solutions developer",
      lead: "I turn business challenges into systems with clear logic, thoughtful interfaces and a reliable technical foundation.",
      body: "I work across product planning, design and development. That lets me see the complete user journey — from the first action to the data available in the control panel.",
      statOneTitle: "Full cycle",
      statOne: "one context from idea to launch",
      statTwoTitle: "Product thinking",
      statTwo: "every feature supports the goal",
    },
    contact: {
      kicker: "Start a project / 2026",
      titleStart: "Have an idea or a task that should be ",
      titleAccent: "automated?",
      text: "Describe what needs to work. I will help turn it into a clear digital product.",
      nameLabel: "Your name",
      namePlaceholder: "Name",
      contactLabel: "How to reach you",
      contactPlaceholder: "@telegram or email",
      taskLabel: "About the challenge",
      taskPlaceholder: "What should work, and for whom?",
      privacy: "The details you provide are used only to respond to your request.",
      submit: "Send via Telegram",
      status: "Your message is ready — send it in the Telegram window that opened.",
      fallback: "Open Telegram manually",
      messageTitle: "New request from the Alexey Worker website",
      messageName: "Name",
      messageContact: "Contact",
      messageTask: "Challenge",
      directTitle: "Or contact me directly",
      telegram: "Telegram",
      email: "Email",
    },
    footer: { text: "Digital products and business automation.", top: "Back to top", telegram: "Telegram" },
    casePage: {
      metaTitle: "PINK CLUB — digital system case study | Alexey Worker",
      metaDescription: "A Telegram product with a Mini App, user journeys, internal economy, administration panel and integrations.",
      back: "All projects",
      badge: "Case 01 / Telegram product",
      intro: "A digital club system inside Telegram: user journeys, internal economy, automation, administration and infrastructure.",
      taskLabel: "Challenge",
      taskTitle: "Build a complete Telegram product, not just a standalone bot",
      taskBodyOne: "The club needs one continuous user journey: product introduction, participation, internal units and feedback — without manually supporting every action.",
      taskBodyTwo: "The solution is designed as a set of connected modules. The interface, business logic and management remain separated without fragmenting the user experience.",
      solutionLabel: "Solution / 04",
      solutionTitle: "The product's core systems",
      functions: [["Telegram-first journeys", "Entry, navigation and key actions live in an environment users already know."], ["Internal economy", "Balances, operations and rules form a separate, controlled system."], ["Administration panel", "The team manages members, content and events without touching the code."], ["Automation", "The system handles standard events, updates statuses and sends notifications automatically."]],
      resultLabel: "Outcome",
      resultTitle: "A foundation the product can grow on",
      resultBody: "The architecture connects the Telegram interface, Mini App, server logic, data storage and administrative workflows. Each module can evolve independently while keeping one product context.",
      note: "Quantitative results are intentionally omitted: this case uses only verified information about the solution structure and logic.",
      tech: "Technology stack",
      next: "Your next product",
      ctaTitle: "Need a system with similar logic?",
      cta: "Discuss the challenge",
    },
  },
} as const;

export function getTranslations(locale: Locale) {
  return translations[locale];
}
